### PR TITLE
Use HTTPS for CDN hrefs

### PR DESCRIPTION
**Pull request by kendaleiv**

### CODE REVIEW

**Comment by hougasian** [comment]
can we just remove all protocols > // ?

**Comment by kendaleiv** [comment]
I've been using **https://** now, rather than **//**, per https://twitter.com/paul_irish/status/588502455530311680.

**Comment by kendaleiv** [comment]
Maybe there's a performance implication with using HTTPS when the site is requested over HTTP. Whatever we choose, it should ideally be consistent.

**Comment by hougasian** [comment]
Let's go with Paul Irish; apparently calling // will call the resource with the same protocol of the calling page. 
http://blog.wikimedia.org/2011/07/19/protocol-relative-urls-enabled-on-test-wikipedia-org/

**Pull request merged**
