### PR TITLE
Run grunt automatically after Core build

### PR DESCRIPTION
**Pull request by kendaleiv**
This implies everything on the developer machine is setup and ready to go. Perhaps we should wait until the necessary prerequisites to the README.md have been merged (see #9) before merging this?

### CODE REVIEW

**Comment by jrusbatch** [comment]
Could also use the [Grunt NuGet package](http://www.nuget.org/packages/Grunt), which will add a `.bin\Grunt.cmd` to the project that you can use to execute your gruntfile.

**Comment by billbogaiv** [comment]
@kendaleiv: the `Grunfile` is in the same directory as the `Core` project, so you just need to call `grunt`.

**Comment by billbogaiv** [comment]
@kendaleiv why not use the NuGet @jrusbatch mentioned?

**Comment by kendaleiv** [comment]
Good idea @jrusbatch. Closing in favor of #31.

**Pull request closed without merging**
