### PR TITLE
[WIP] Convert to vs2017 format

### PR DESCRIPTION
**Pull request by snebjorn**
#153

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
Thanks for taking the time to do this. I'll look at it as soon as I can, but the team is really busy right now so not sure I can give you an ETA.

**Comment by kendaleiv** [comment]
It opens in VS2017 and `UsageSampleMvc.AspNetCore` works! ✨

`UsageSample` and some other projects don't appear to run, but that could be fixed in another PR if the core functionality is sound. That's assuming they work prior to this using VS2015, too... :smiley:

**Comment by snebjorn** [comment]
Checkout issue #153 I've made some additional comments

**Comment by kendaleiv** [comment]
Merging this into a `vnext` branch.

**Pull request merged**
